

services:
  seiko-app-dev:
    container_name: seiko-app-dev
    build: .
    ports:
      - "${FLASK_RUN_PORT}:${FLASK_RUN_PORT}"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - IS_DEBUG=True
      - IS_LOGGING=True
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    command: flask run --host=${FLASK_RUN_HOST} --port=${FLASK_RUN_PORT}


  


